export const categories = [
    {
        name: 'frontend',
        label: 'Animated Libraries',
        description: "Libraries that bring engaging animations.",
        filePath: 'Resources/animation-libraries.json',
        background: "#1ABC9C",
        icon: `<img src="./Assets/animation.svg" alt="icons" />`,
    },
    {
        name: 'free web templates',
        label: 'Free Web Templates',
        description: "Download free web templates for your designs.",
        filePath: 'Resources/web-templates.json',
        background: "#E74C3C",
        icon: `<img src="./Assets/ai.svg" alt="icons" />`,
    },
    {
        name: 'components',
        label: 'Components Libraries',
        description: "Collections of reusable UI components.",
        filePath: 'Resources/components.json',
        background: "#F1C40F",
        icon: `<img src="./Assets/components.svg" alt="components" />`,
    },
    {
        name: 'seo',
        label: 'SEO Tools',
        description: "Tools to optimize your website for SEO.",
        filePath: 'Resources/seo.json',
        background: "#27AE60",
        icon: `<img src="./Assets/web.svg" alt="seo" />`,
    },
    {
        name: 'tools',
        label: 'Development Tools',
        description: "Tools designed to streamline development.",
        filePath: 'Resources/tools.json',
        background: "#C0392B",
        icon: `<img src="./Assets/tools.svg" alt="tools" />`,
    },
    {
        name: 'icons',
        label: 'Icons',
        description: "Discover and download icon sets for your projects.",
        filePath: 'Resources/icons.json',
        background: "#4A90E2",
        icon: `<img src="./Assets/icons.svg" alt="icons" />`,
    },
    {
        name: '3d',
        label: '3D',
        description: "Resources for creating and using 3D graphics.",
        filePath: 'Resources/3d.json',
        background: "#9B59B6",
        icon: `<img src="./Assets/3d.svg" alt="3D" />`,
    },
    {
        name: 'background',
        label: 'Background',
        description: "Background patterns to enhance your designs.",
        filePath: 'Resources/background.json',
        background: "#3498DB",
        icon: `<img src="./Assets/backgrounds.svg" alt="background" />`,
    },
    {
        name: 'blog',
        label: 'Dev Blog',
        description: "Inspiration to fuel your blogging journey.",
        filePath: 'Resources/blog.json',
        background: "#2ECC71",
        icon: `<img src="./Assets/blogs.svg" alt="blog" />`,
    },
    {
        name: 'colors',
        label: 'Colors',
        description: "Palettes to select and manage color schemes.",
        filePath: 'Resources/colors.json',
        background: "#E74C3C",
        icon: `<img src="./Assets/colors.svg" alt="colors" />`,
    },
    {
        name: 'illustrations',
        label: 'Illustrations',
        description: "A variety of illustrations for creative and marketing needs.",
        filePath: 'Resources/illustrations.json',
        background: "#1ABC9C",
        icon: `<img src="./Assets/illustrations.svg" alt="illustrations" />`,
    },
    {
        name: 'libraries',
        label: 'UI Libraries',
        description: "A curated list of libraries to build stunning user interfaces.",
        filePath: 'Resources/libraries.json',
        background: "#D35400",
        icon: `<img src="./Assets/libraries.svg" alt="UI Libraries" />`,
    },
    {
        name: 'photos',
        label: 'Photos',
        description: "High-quality photos to enhance your visual projects.",
        filePath: 'Resources/photos.json',
        background: "#8E44AD",
        icon: `<img src="./Assets/photos.svg" alt="photos" />`,
    },
    {
        name: 'font',
        label: 'Fonts',
        description: "Explore a wide range of fonts to suit every design style.",
        filePath: 'Resources/fonts.json',
        background: "#27AE60",
        icon: `<img src="./Assets/typography.svg" alt="fonts" />`,
    },
    {
        name: 'video',
        label: 'Video',
        description: "Resources for video editing, creation, and inspiration.",
        filePath: 'Resources/video.json',
        background: "#2980B9",
        icon: `<img src="./Assets/videos.svg" alt="video" />`,
    },
    {
        name: 'low-code/no-code',
        label: 'Low-Code/No-Code Tools',
        description: "Build applications with minimal coding effort.",
        filePath: 'Resources/low-code.json',
        background: "#E67E22",
        icon: `<img src="./Assets/code.svg" alt="icons" />`,
    },
    {
        name: 'design inspiration',
        label: 'Design Inspirations',
        description: "Get inspired by creative design trends and resources.",
        filePath: 'Resources/design.json',
        background: "#16A085",
        icon: `<img src="./Assets/design.svg" alt="icons" />`,
    },
    {
        name: 'deployments',
        label: 'Deployments',
        description: "Tools and platforms to deploy your applications smoothly.",
        filePath: 'Resources/deployment.json',
        background: "#C0392B",
        icon: `<img src="./Assets/web.svg" alt="icons" />`,
    },
    {
        name: 'database',
        label: 'Database',
        description: "Resources and tools for effective data management.",
        filePath: 'Resources/database.json',
        background: "#8E44AD",
        icon: `<img src="./Assets/database.svg" alt="icons" />`,
    },
    {
        name: 'ai',
        label: 'AI Builders',
        description: "Tools and platforms to build and integrate AI solutions.",
        filePath: 'Resources/ai.json',
        background: "#D35400",
        icon: `<img src="./Assets/ai.svg" alt="icons" />`,
    },
    {
        name: 'tailwind',
        label: 'Tailwind Components',
        description: "Components built with Tailwind CSS for modern designs.",
        filePath: 'Resources/tailwind.json',
        background: "#27AE60",
        icon: `<img src="./Assets/tailwind.svg" alt="icons" />`,
    },
    {
        name: 'shadcn',
        label: 'ShadCN Components',
        description: "Modern UI components for rapid and stylish development.",
        filePath: 'Resources/shadcn.json',
        background: "#2980B9",
        icon: `<img src="./Assets/code.svg" alt="icons" />`,
    },
    {
        name: 'freelance',
        label: 'Freelance Platforms',
        description: "Platforms that connect freelancers with project opportunities.",
        filePath: 'Resources/freelance.json',
        background: "#1ABC9C",
        icon: `<img src="./Assets/coin.svg" alt="icons" />`,
    },
    {
        name: 'learning',
        label: 'Learning Platforms',
        description: "Online resources and tutorials to boost your skills.",
        filePath: 'Resources/learning-resources.json',
        background: "#E74C3C",
        icon: `<img src="./Assets/book.svg" alt="icons" />`,
    },
    {
        name: 'web',
        label: 'Web Builder Platforms',
        description: "Platforms that simplify website creation and management.",
        filePath: 'Resources/builder.json',
        background: "#27AE60",
        icon: `<img src="./Assets/ai.svg" alt="icons" />`,
    },
    {
        name: 'accessibility',
        label: 'Accessibility',
        description: "Tools and resources to create accessible web experiences.",
        filePath: 'Resources/accessibility.json',
        background: "#E75480",
        icon: `<img src="./Assets/accessibility.svg" alt="accessibility" />`,
    },
    {
        name: 'security',
        label: 'Web Security',
        description: "Resources to help secure your web applications effectively.",
        filePath: 'Resources/security.json',
        background: "#F39C12",
        icon: `<img src="./Assets/security.svg" alt="security" />`,
    },
];
